import base64
import io
import json
import math
import re
from typing import Any, Dict, List, Optional, Tuple

try:
    from pypdf import PdfReader, PdfWriter
    from pypdf.generic import NameObject, BooleanObject, DictionaryObject       
    from reportlab.lib.pagesizes import A4, LETTER
    from reportlab.lib.units import mm, inch
    from reportlab.pdfgen import canvas
    from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY
except ImportError as e:
    raise ImportError(f"Missing dependencies: {e}")

# --- Visible synthetic mark ---------------------------------------------------
#
# ClientSynth's machine-readable provenance -- the HMAC watermark in
# lib/population/watermark.ts -- travels with the *records*. A generated PDF is
# an asset, and until now it carried nothing a person could see: a downloaded
# specimen certificate, invoice or licence was indistinguishable, on screen or
# on paper, from a real one.
#
# Every PDF this service hands back is stamped on the way out. All four builders
# -- fill, content, template, generate -- return through _encode_marked(), so a
# fifth builder cannot quietly forget the mark; it would have to avoid the
# encoder on purpose.
#
# There is deliberately no configuration switch to suppress this. A mark a flag
# can remove is not a boundary, and the flag is what gets set in a hurry the day
# someone wants a clean-looking sample. If the mark cannot be applied, PDF
# generation fails rather than emitting an unmarked synthetic document.

MARK_TEXT = "SYNTHETIC"
MARK_SUBTEXT = "NOT A VALID DOCUMENT"
MARK_FOOTER = (
    "Synthetic specimen generated by ClientSynth -- not a valid document, and "
    "not a record of any real person, company or transaction."
)


def _mark_overlay(width: float, height: float) -> bytes:
    """A one-page PDF carrying the mark, sized to the page it will cover."""
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=(width, height))
    diag = math.hypot(width, height)

    def _fit(text: str, size: float, limit: float, floor: float) -> float:
        """Largest size at or below `size` whose string fits inside `limit`."""
        while size > floor and c.stringWidth(text, "Helvetica-Bold", size) > limit:
            size -= 0.5
        return size

    # Diagonal body mark, corner to corner so it cannot be cropped off. The
    # fill carries its own alpha: setFillColor() *overwrites* the alpha set by
    # setFillAlpha(), so an rgba colour is the only order-independent way to
    # get a translucent mark that does not bury the content underneath it.
    c.saveState()
    c.setFillColor(colors.Color(0.42, 0.42, 0.45, alpha=0.16))
    c.translate(width / 2.0, height / 2.0)
    c.rotate(math.degrees(math.atan2(height, width)))

    # Kept well inside the diagonal: text drawn near the corners has nowhere to
    # put its own height, and its ascenders clip against the page edge.
    limit = diag * 0.62
    size = _fit(MARK_TEXT, min(diag * 0.085, 72.0), limit, 10.0)
    c.setFont("Helvetica-Bold", size)
    c.drawCentredString(0, size * 0.20, MARK_TEXT)

    sub = _fit(MARK_SUBTEXT, size * 0.36, limit, 6.0)
    c.setFont("Helvetica-Bold", sub)
    c.drawCentredString(0, -size * 0.72, MARK_SUBTEXT)
    c.restoreState()

    # Footer line -- legible rather than decorative, so it stays fully opaque.
    c.saveState()
    c.setFillColor(colors.Color(0.69, 0.0, 0.13, alpha=1.0))
    fs = _fit(MARK_FOOTER, 7.5, width * 0.94, 4.0)
    c.setFont("Helvetica-Bold", fs)
    c.drawCentredString(width / 2.0, max(5.0, height * 0.012), MARK_FOOTER)
    c.restoreState()

    c.showPage()
    c.save()
    return buf.getvalue()


def _mark_synthetic(pdf_bytes: bytes) -> bytes:
    """Stamp every page of a finished PDF, and record the fact in its metadata.

    Raises on failure. Callers wrap generation in try/except and report the
    error, which is the intended outcome: no mark, no document.
    """
    reader = PdfReader(io.BytesIO(pdf_bytes))
    writer = PdfWriter()
    # Clone rather than re-add pages: pdf_fill's output carries an /AcroForm and
    # /NeedAppearances, and rebuilding page-by-page would drop the form fields.
    writer.clone_document_from_reader(reader)

    for page in writer.pages:
        box = page.mediabox
        width = float(box.width)
        height = float(box.height)
        if width <= 0 or height <= 0:
            raise ValueError(f"Cannot mark a page with size {width}x{height}")
        # Built in unrotated page space on purpose: a /Rotate page turns the
        # mark with its content, so the two always read the same way up.
        overlay = PdfReader(io.BytesIO(_mark_overlay(width, height))).pages[0]
        page.merge_page(overlay)

    writer.add_metadata(
        {
            "/Producer": "ClientSynth (synthetic data generator)",
            "/Subject": "SYNTHETIC SPECIMEN - not a valid document",
            "/Synthetic": "true",
        }
    )

    out = io.BytesIO()
    writer.write(out)
    return out.getvalue()


def _encode_marked(pdf_bytes: bytes) -> str:
    """The single exit for generated PDF bytes: mark, then base64-encode."""
    return base64.b64encode(_mark_synthetic(pdf_bytes)).decode("ascii")


def pdf_fill(pdf_base64: str, data: Dict[str, Any]) -> Dict[str, Any]:
    try:
        raw = base64.b64decode(pdf_base64)
        r = PdfReader(io.BytesIO(raw))
        w = PdfWriter()
        for p in r.pages:
            w.add_page(p)
        
        try:
            root = r.trailer["/Root"]
            acro = root.get("/AcroForm")
            if acro is not None:
                w._root_object.update({NameObject("/AcroForm"): acro})
        except Exception:
            pass
        
        if data:
            fields_map = {str(k): str(v) for k, v in data.items()}
            for page in w.pages:
                w.update_page_form_field_values(page, fields_map)
        
        try:
            root = w._root_object
            if "/AcroForm" in root:
                af = root["/AcroForm"]
                af.update({NameObject("/NeedAppearances"): BooleanObject(True)})
            else:
                root.update({NameObject("/AcroForm"): DictionaryObject({NameObject("/NeedAppearances"): BooleanObject(True)})})
        except Exception:
            pass
        
        out = io.BytesIO()
        w.write(out)
        return {"success": True, "pdf_base64": _encode_marked(out.getvalue())}
    except Exception as e:
        return {"success": False, "error": str(e)}

def pdf_content_create(title: str, content: str, page_size: str = "A4", margin_mm: int = 20) -> Dict[str, Any]:
    """Create a PDF with actual text content (not form fields)"""
    try:
        if not title.strip():
            return {"success": False, "error": "title required"}
        if not content:
            return {"success": False, "error": "content required"}
        if page_size not in {"A4", "LETTER"}:
            return {"success": False, "error": "bad page_size"}

        ps = A4 if page_size == "A4" else LETTER
        buf = io.BytesIO()
        c = canvas.Canvas(buf, pagesize=ps)
        pw, ph = ps
        m = float(margin_mm) * mm

        c.setTitle(title.strip())
        
        # Draw title
        c.setFont("Helvetica-Bold", 16)
        c.drawString(m, ph - m, title.strip())
        
        # Draw content
        y = ph - m - 15 * mm
        c.setFont("Helvetica", 10)
        
        # Split content into lines and handle wrapping
        lines = content.split('\n')
        line_height = 4 * mm
        max_width = pw - 2 * m
        
        for line in lines:
            # Handle empty lines
            if not line.strip():
                y -= line_height
                if y < m:
                    c.showPage()
                    c.setFont("Helvetica", 10)
                    y = ph - m
                continue
            
            # Check if line starts with special markers for formatting
            if line.strip().startswith('**') and line.strip().endswith('**'):
                # Bold section header
                c.setFont("Helvetica-Bold", 12)
                text = line.strip().replace('**', '')
                c.drawString(m, y, text)
                c.setFont("Helvetica", 10)
                y -= line_height * 1.5
            elif line.strip().startswith('- '):
                # Bullet point
                c.drawString(m + 5*mm, y, '•')
                c.drawString(m + 10*mm, y, line.strip()[2:])
                y -= line_height
            else:
                # Regular text - wrap if needed
                words = line.split()
                current_line = ""
                for word in words:
                    test_line = current_line + " " + word if current_line else word
                    if c.stringWidth(test_line, "Helvetica", 10) < max_width:
                        current_line = test_line
                    else:
                        if current_line:
                            c.drawString(m, y, current_line)
                            y -= line_height
                            if y < m:
                                c.showPage()
                                c.setFont("Helvetica", 10)
                                y = ph - m
                        current_line = word
                
                if current_line:
                    c.drawString(m, y, current_line)
                    y -= line_height
            
            # Check if we need a new page
            if y < m:
                c.showPage()
                c.setFont("Helvetica", 10)
                y = ph - m

        c.save()

        pdf_b64 = _encode_marked(buf.getvalue())
        return {
            "success": True,
            "title": title.strip(),
            "page_size": page_size,
            "pdf_base64": pdf_b64,
        }
    except Exception as e:
        return {"success": False, "error": str(e)}

def pdf_template_create(title: str, fields: List[Dict[str, Any]], page_size: str = "A4", margin_mm: int = 20) -> Dict[str, Any]:
    try:
        if not title.strip():
            return {"success": False, "error": "title required"}
        if not fields:
            return {"success": False, "error": "fields required"}
        if page_size not in {"A4", "LETTER"}:
            return {"success": False, "error": "bad page_size"}

        ps = A4 if page_size == "A4" else LETTER
        buf = io.BytesIO()
        c = canvas.Canvas(buf, pagesize=ps)
        pw, ph = ps
        m = float(margin_mm) * mm

        c.setTitle(title.strip())
        c.setFont("Helvetica-Bold", 16)
        c.drawString(m, ph - m, title.strip())

        y = ph - m - 15 * mm
        c.setFont("Helvetica", 11)

        n = min(len(fields), 100)
        fh = 8 * mm
        gap = 6 * mm
        tfw = pw - 2 * m

        for i in range(n):
            f = fields[i]
            if not isinstance(f, dict):
                return {"success": False, "error": "bad field"}
            name = str(f.get("name", "")).strip()
            if not name:
                return {"success": False, "error": "field name required"}
            label = str(f.get("label", name)).strip()
            c.drawString(m, y + fh + 2, label)
            c.acroForm.textfield(
                name=name,
                x=m,
                y=y,
                width=tfw,
                height=fh,
                borderStyle="underlined",
            )
            y -= (fh + gap)
            if y < m + fh + gap:
                c.showPage()
                c.setFont("Helvetica", 11)
                y = ph - m

        c.showPage()
        c.save()

        pdf_b64 = _encode_marked(buf.getvalue())
        return {
            "success": True,
            "title": title.strip(),
            "page_size": page_size,
            "field_count": n,
            "pdf_base64": pdf_b64,
        }
    except Exception as e:
        return {"success": False, "error": str(e)}

def pdf_template_generate(
    template_config: Dict[str, Any],
    data: Dict[str, Any],
    page_size: str = "A4",
    margin_mm: int = 20
) -> Dict[str, Any]:
    """
    Generate PDF from template configuration with full layout preservation.
    Supports placeholders, dynamic tables, page breaks, fonts, and margins.
    
    template_config structure:
    {
        "title": "Document Title",
        "pageSize": "A4" | "LETTER",
        "marginMm": 20,
        "fonts": {
            "default": "Helvetica",
            "defaultSize": 11,
            "title": {"family": "Helvetica-Bold", "size": 16},
            "header": {"family": "Helvetica-Bold", "size": 12}
        },
        "sections": [
            {
                "type": "title",
                "content": "{{title}}"  // Supports placeholders
            },
            {
                "type": "text",
                "content": "{{description}}",
                "font": {"family": "Helvetica", "size": 11}
            },
            {
                "type": "table",
                "headers": ["Column 1", "Column 2"],
                "rows": "{{table_data}}",  // Placeholder for dynamic data
                "style": {
                    "headerBackground": "#CCCCCC",
                    "alternateRows": True,
                    "columnWidths": [0.5, 0.5]
                },
                "pageBreakBefore": False,
                "pageBreakAfter": False
            },
            {
                "type": "pageBreak"
            }
        ]
    }
    """
    try:
        if not template_config:
            return {"success": False, "error": "template_config required"}
        if page_size not in {"A4", "LETTER"}:
            return {"success": False, "error": "bad page_size"}

        ps = A4 if page_size == "A4" else LETTER
        m = float(margin_mm) * mm
        
        # Create buffer and document
        buf = io.BytesIO()
        doc = SimpleDocTemplate(
            buf,
            pagesize=ps,
            rightMargin=m,
            leftMargin=m,
            topMargin=m,
            bottomMargin=m
        )
        
        # Get styles
        styles = getSampleStyleSheet()
        
        # Extract font configuration
        font_config = template_config.get("fonts", {})
        default_font = font_config.get("default", "Helvetica")
        default_size = font_config.get("defaultSize", 11)
        title_font = font_config.get("title", {"family": "Helvetica-Bold", "size": 16})
        header_font = font_config.get("header", {"family": "Helvetica-Bold", "size": 12})
        
        # Create custom styles
        custom_styles = {
            "title": ParagraphStyle(
                "CustomTitle",
                parent=styles["Heading1"],
                fontName=title_font.get("family", "Helvetica-Bold"),
                fontSize=title_font.get("size", 16),
                spaceAfter=12,
                alignment=TA_LEFT
            ),
            "header": ParagraphStyle(
                "CustomHeader",
                parent=styles["Heading2"],
                fontName=header_font.get("family", "Helvetica-Bold"),
                fontSize=header_font.get("size", 12),
                spaceAfter=8,
                alignment=TA_LEFT
            ),
            "normal": ParagraphStyle(
                "CustomNormal",
                parent=styles["Normal"],
                fontName=default_font,
                fontSize=default_size,
                spaceAfter=6,
                alignment=TA_LEFT
            )
        }
        
        # Build story (content elements)
        story = []
        sections = template_config.get("sections", [])
        
        for section in sections:
            section_type = section.get("type")
            
            if section_type == "title":
                # Title section
                content = _replace_placeholders(section.get("content", ""), data)
                if content:
                    story.append(Paragraph(content, custom_styles["title"]))
                    story.append(Spacer(1, 6*mm))
                    
            elif section_type == "text":
                # Text section
                content = _replace_placeholders(section.get("content", ""), data)
                if content:
                    section_font = section.get("font", {})
                    text_style = ParagraphStyle(
                        "SectionText",
                        parent=custom_styles["normal"],
                        fontName=section_font.get("family", default_font),
                        fontSize=section_font.get("size", default_size),
                        spaceAfter=section.get("spaceAfter", 6)
                    )
                    flowables = _build_markdown_flowables(
                        content,
                        text_style,
                        ps[0] - 2 * m,
                        default_font,
                        default_size,
                        header_font
                    )
                    if flowables:
                        story.extend(flowables)
                    else:
                        story.append(Paragraph(content.replace("\n", "<br/>"), text_style))
                    
            elif section_type == "table":
                # Dynamic table section
                if section.get("pageBreakBefore", False):
                    story.append(PageBreak())
                
                headers = section.get("headers", []) or []
                rows_data = section.get("rows")
                
                # Handle placeholder for rows data
                if isinstance(rows_data, str) and rows_data.startswith("{{") and rows_data.endswith("}}"):
                    placeholder = rows_data[2:-2].strip()
                    rows_data = data.get(placeholder, [])
                
                parsed_headers = []
                parsed_rows = []

                if isinstance(rows_data, str):
                    parsed_headers, parsed_rows = _parse_markdown_table(rows_data)
                    rows_data = parsed_rows
                    if not headers and parsed_headers:
                        headers = parsed_headers
                elif isinstance(rows_data, dict):
                    potential_headers = rows_data.get("headers")
                    potential_rows = rows_data.get("rows") or rows_data.get("data") or rows_data.get("values")
                    if isinstance(potential_rows, list):
                        rows_data = potential_rows
                    else:
                        rows_data = []
                    if not headers and isinstance(potential_headers, list):
                        headers = potential_headers
                if not isinstance(rows_data, list):
                    rows_data = []

                if not headers and rows_data:
                    first_row = rows_data[0]
                    if isinstance(first_row, dict):
                        headers = list(first_row.keys())
                    elif isinstance(first_row, (list, tuple)):
                        headers = [f"Column {i+1}" for i in range(len(first_row))]

                # Build table data
                table_data = []
                if headers:
                    table_data.append([str(h) for h in headers])

                # Ensure consistent row width
                target_length = len(headers) if headers else max((len(row) for row in rows_data if isinstance(row, (list, tuple))), default=0)

                for row in rows_data:
                    if isinstance(row, dict):
                        row_values = [
                            str(_extract_dict_value_for_header(row, header))
                            for header in headers
                        ]
                    elif isinstance(row, (list, tuple)):
                        row_values = [str(cell) for cell in row]
                    else:
                        continue

                    if headers:
                        if len(row_values) < len(headers):
                            row_values.extend([""] * (len(headers) - len(row_values)))
                        elif len(row_values) > len(headers):
                            row_values = row_values[:len(headers)]
                    elif target_length:
                        if len(row_values) < target_length:
                            row_values.extend([""] * (target_length - len(row_values)))
                        elif len(row_values) > target_length:
                            row_values = row_values[:target_length]

                    table_data.append(row_values)

                # If no rows were added but we have headers, keep at least the header row
                if not table_data and headers:
                    table_data.append([str(h) for h in headers])

                if table_data:
                    table_style_config = section.get("style", {})
                    col_widths = table_style_config.get("columnWidths")
                    if col_widths and headers and len(col_widths) == len(headers):
                        available_width = ps[0] - 2 * m
                        col_widths = [w * available_width for w in col_widths]
                    elif headers and not col_widths and len(headers) > 0:
                        available_width = ps[0] - 2 * m
                        col_widths = [available_width / len(headers)] * len(headers)
                    else:
                        col_widths = None

                    try:
                        table = Table(table_data, colWidths=col_widths)
                        table.hAlign = "LEFT"
                    except Exception:
                        # Fallback: render as paragraphs if table creation fails
                        fallback_text = _markdown_to_paragraph_text(_table_to_markdown(headers, rows_data))
                        story.append(Paragraph(fallback_text, custom_styles["normal"]))
                        story.append(Spacer(1, 6 * mm))
                        continue

                    table_style = [
                        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                        ("FONTNAME", (0, 0), (-1, -1), default_font),
                        ("FONTSIZE", (0, 0), (-1, -1), default_size),
                        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                        ("TOPPADDING", (0, 0), (-1, -1), 6),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ]

                    if headers:
                        table_style.extend([
                            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(table_style_config.get("headerBackground", "#2D3748"))),
                            ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                            ("FONTNAME", (0, 0), (-1, 0), header_font.get("family", "Helvetica-Bold")),
                            ("FONTSIZE", (0, 0), (-1, 0), header_font.get("size", 12)),
                            ("BOTTOMPADDING", (0, 0), (-1, 0), 12),
                            ("TOPPADDING", (0, 0), (-1, 0), 12),
                        ])

                        if len(table_data) > 1:
                            table_style.append(("BACKGROUND", (0, 1), (-1, -1), colors.white))
                        if table_style_config.get("alternateRows", False):
                            for i in range(1, len(table_data)):
                                if i % 2 == 1:
                                    table_style.append(("BACKGROUND", (0, i), (-1, i), colors.HexColor("#F7FAFC")))
                    else:
                        if table_style_config.get("alternateRows", False):
                            for i in range(len(table_data)):
                                if i % 2 == 1:
                                    table_style.append(("BACKGROUND", (0, i), (-1, i), colors.HexColor("#F7FAFC")))

                    table.setStyle(TableStyle(table_style))
                    story.append(table)
                    story.append(Spacer(1, 6*mm))
                
                if section.get("pageBreakAfter", False):
                    story.append(PageBreak())
                    
            elif section_type == "pageBreak":
                # Explicit page break
                story.append(PageBreak())
                
            elif section_type == "spacer":
                # Spacer
                height_mm = section.get("heightMm", 6)
                story.append(Spacer(1, height_mm * mm))
        
        # Build PDF
        doc.build(story)
        
        pdf_b64 = _encode_marked(buf.getvalue())
        return {
            "success": True,
            "pdf_base64": pdf_b64,
            "page_size": page_size,
        }
    except Exception as e:
        return {"success": False, "error": str(e)}


def _normalize_table_key(value: Any) -> str:
    return ''.join(ch.lower() for ch in str(value) if ch.isalnum())


def _extract_dict_value_for_header(row: Dict[str, Any], header: str) -> Any:
    if not isinstance(row, dict):
        return ""

    # Direct match
    if header in row:
        return row[header]

    normalized_header = _normalize_table_key(header)
    for key, value in row.items():
        if _normalize_table_key(key) == normalized_header:
            return value

    return ""


def _parse_markdown_table(table_str: str) -> Tuple[List[str], List[List[str]]]:
    headers: List[str] = []
    rows: List[List[str]] = []

    if not isinstance(table_str, str):
        return headers, rows

    lines = table_str.splitlines()
    for line in lines:
        stripped = line.strip()
        if not stripped or "|" not in stripped:
            continue

        # Skip separator rows
        candidate = stripped.replace("|", "").strip()
        if candidate and all(ch in "-:=" for ch in candidate):
            continue

        parts = [cell.strip() for cell in stripped.strip("|").split("|")]
        parts = [cell for cell in parts if cell]
        if not parts:
            continue

        # Skip rows that are only separators after trimming
        if all(not cell or set(cell) <= set("-:= ") for cell in parts):
            continue

        if not headers:
            headers = parts
            continue

        rows.append(parts)

    return headers, rows


def _block_is_markdown_table(block: str) -> bool:
    if not isinstance(block, str):
        return False
    lines = [line for line in block.splitlines() if line.strip()]
    if len(lines) < 2:
        return False
    if not all('|' in line for line in lines[:2]):
        return False
    header_line = lines[0]
    divider_line = lines[1]
    return ':' in divider_line or '-' in divider_line


def _markdown_to_paragraph_text(text: str) -> str:
    if not isinstance(text, str):
        return str(text)

    lines = []
    for raw_line in text.splitlines():
        line = raw_line.rstrip()
        stripped = line.strip()

        if not stripped:
            lines.append("")
            continue

        # Headings
        if stripped.startswith("### "):
            stripped = f"<b>{stripped[4:].strip()}</b>"
        elif stripped.startswith("## "):
            stripped = f"<b>{stripped[3:].strip()}</b>"
        elif stripped.startswith("# "):
            stripped = f"<b>{stripped[2:].strip()}</b>"

        # Bullet points
        elif stripped.startswith("- "):
            stripped = f"&bull; {stripped[2:].strip()}"
        elif stripped.startswith("* "):
            stripped = f"&bull; {stripped[2:].strip()}"

        # Bold text
        stripped = re.sub(r"\*\*(.*?)\*\*", r"<b>\1</b>", stripped)

        lines.append(stripped)

    # Collapse multiple consecutive blank lines
    paragraph_lines: List[str] = []
    blank_count = 0
    for line in lines:
        if not line:
            blank_count += 1
            if blank_count <= 1:
                paragraph_lines.append("")
        else:
            blank_count = 0
            paragraph_lines.append(line)

    return "<br/>".join(paragraph_lines)


def _build_markdown_flowables(
    content: str,
    text_style: ParagraphStyle,
    available_width: float,
    default_font: str,
    default_size: int,
    header_font: Dict[str, Any]
) -> List[Any]:
    flowables: List[Any] = []
    if not isinstance(content, str):
        flowables.append(Paragraph(str(content), text_style))
        return flowables

    blocks = re.split(r"\n{2,}", content.strip())
    for block in blocks:
        normalized_block = block.strip()
        if not normalized_block:
            continue

        if _block_is_markdown_table(normalized_block):
            headers, rows = _parse_markdown_table(normalized_block)
            if headers or rows:
                table_data: List[List[str]] = []
                if headers:
                    table_data.append([str(h) for h in headers])
                for row in rows:
                    table_data.append([str(cell) for cell in row])

                if table_data:
                    try:
                        col_widths = None
                        if headers and len(headers) > 0:
                            col_widths = [available_width / len(headers)] * len(headers)

                        table = Table(table_data, colWidths=col_widths)
                        table.hAlign = "LEFT"
                        table.repeatRows = 1 if headers else 0

                        table_style = [
                            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                            ("FONTNAME", (0, 0), (-1, -1), default_font),
                            ("FONTSIZE", (0, 0), (-1, -1), default_size),
                            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                            ("TOPPADDING", (0, 0), (-1, -1), 6),
                            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                        ]

                        if headers:
                            table_style.extend([
                                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2D3748")),
                                ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                                ("FONTNAME", (0, 0), (-1, 0), header_font.get("family", "Helvetica-Bold")),
                                ("FONTSIZE", (0, 0), (-1, 0), header_font.get("size", 12)),
                                ("BOTTOMPADDING", (0, 0), (-1, 0), 12),
                                ("TOPPADDING", (0, 0), (-1, 0), 12),
                            ])
                            if len(table_data) > 1:
                                table_style.append(("BACKGROUND", (0, 1), (-1, -1), colors.white))

                        table.setStyle(TableStyle(table_style))
                        flowables.append(table)
                        flowables.append(Spacer(1, 6 * mm))
                    except Exception:
                        fallback_text = _markdown_to_paragraph_text(normalized_block)
                        if fallback_text:
                            flowables.append(Paragraph(fallback_text, text_style))
        else:
            paragraph_text = _markdown_to_paragraph_text(normalized_block)
            if paragraph_text:
                flowables.append(Paragraph(paragraph_text, text_style))

    return flowables


def _table_to_markdown(headers: List[str], rows: List[List[str]]) -> str:
    header_line = "| " + " | ".join(str(h) for h in headers) + " |" if headers else ""
    divider_line = "| " + " | ".join("---" for _ in headers) + " |" if headers else ""
    row_lines = ["| " + " | ".join(str(cell) for cell in row) + " |" for row in rows]
    lines = [line for line in [header_line, divider_line] + row_lines if line]
    return "\n".join(lines)


def _replace_placeholders(text: str, data: Dict[str, Any]) -> str:
    """Replace placeholders like {{key}} with values from data dict."""
    if not isinstance(text, str):
        return str(text)
    
    result = text
    import re
    pattern = r'\{\{(\w+)\}\}'
    
    def replace_func(match):
        key = match.group(1)
        value = data.get(key, "")
        return str(value) if value is not None else ""
    
    result = re.sub(pattern, replace_func, result)
    return result


if __name__ == "__main__":
    import sys
    import json
    import os
    
    if len(sys.argv) < 2:
        print(json.dumps({"success": False, "error": "Missing command"}))
        sys.exit(1)
    
    command = sys.argv[1]
    
    if command == "generate":
        # New template-based generation command
        if len(sys.argv) < 6:
            print(json.dumps({"success": False, "error": "Missing generate arguments"}))
            sys.exit(1)
        
        template_file = sys.argv[2]
        data_file = sys.argv[3]
        page_size = sys.argv[4]
        margin_mm = int(sys.argv[5])
        
        try:
            with open(template_file, 'r') as f:
                template_config = json.load(f)
            with open(data_file, 'r') as f:
                data = json.load(f)
        except Exception as e:
            print(json.dumps({"success": False, "error": f"Failed to read files: {e}"}))
            sys.exit(1)
        
        result = pdf_template_generate(template_config, data, page_size, margin_mm)
        print(json.dumps(result))
        
    elif command == "content":
        if len(sys.argv) < 5:
            print(json.dumps({"success": False, "error": "Missing content arguments"}))
            sys.exit(1)
        
        title = sys.argv[2]
        content = sys.argv[3]
        page_size = sys.argv[4]
        margin_mm = int(sys.argv[5]) if len(sys.argv) > 5 else 20
        
        result = pdf_content_create(title, content, page_size, margin_mm)
        print(json.dumps(result))
        
    elif command == "template":
        if len(sys.argv) < 6:
            print(json.dumps({"success": False, "error": "Missing template arguments"}))
            sys.exit(1)
        
        title = sys.argv[2]
        fields_file = sys.argv[3]
        page_size = sys.argv[4]
        margin_mm = int(sys.argv[5])
        
        try:
            with open(fields_file, 'r') as f:
                fields = json.load(f)
        except Exception as e:
            print(json.dumps({"success": False, "error": f"Failed to read fields file: {e}"}))
            sys.exit(1)
        
        result = pdf_template_create(title, fields, page_size, margin_mm)       
        print(json.dumps(result))
        
    elif command == "fill":
        if len(sys.argv) < 4:
            print(json.dumps({"success": False, "error": "Missing fill arguments"}))
            sys.exit(1)

        pdf_base64 = sys.argv[2]
        data_file = sys.argv[3]
        
        try:
            with open(data_file, 'r') as f:
                data = json.load(f)
        except Exception as e:
            print(json.dumps({"success": False, "error": f"Failed to read data file: {e}"}))
            sys.exit(1)

        result = pdf_fill(pdf_base64, data)
        print(json.dumps(result))
        
    elif command == "generate":
        # Template-based generation command
        if len(sys.argv) < 6:
            print(json.dumps({"success": False, "error": "Missing generate arguments"}))
            sys.exit(1)
        
        template_file = sys.argv[2]
        data_file = sys.argv[3]
        page_size = sys.argv[4]
        margin_mm = int(sys.argv[5])
        
        try:
            with open(template_file, 'r') as f:
                template_config = json.load(f)
            with open(data_file, 'r') as f:
                data = json.load(f)
        except Exception as e:
            print(json.dumps({"success": False, "error": f"Failed to read files: {e}"}))
            sys.exit(1)
        
        result = pdf_template_generate(template_config, data, page_size, margin_mm)
        print(json.dumps(result))

    else:
        print(json.dumps({"success": False, "error": f"Unknown command: {command}"}))
        sys.exit(1)

