/**
 * Emit cross-language watermark conformance vectors.
 *
 * ClientSynth signs; Cosolvent verifies. The two implementations must build
 * byte-identical canonical payloads, so this writes a set of deliberately
 * awkward records (unicode, nesting, numeric edges, key ordering, escapes)
 * stamped with a known secret. Cosolvent's
 * `tests/unit/test_watermark_conformance.py` reads the file and asserts every
 * vector verifies — catching any drift between the two canonicalisers.
 *
 *   npx tsx scripts/watermark-conformance.ts <out.json> [secret]
 */

import { writeFileSync } from "node:fs"
import { canonicalPayload, sign, stamp, WATERMARK_ALGO } from "../lib/population/watermark"

const CONFORMANCE_SECRET = "conformance-secret-do-not-use-in-production"

interface Vector {
  name: string
  participant_type: string
  external_id: string
  fields: Record<string, unknown>
}

const VECTORS: Vector[] = [
  {
    name: "plain ascii",
    participant_type: "producer",
    external_id: "cs-0001",
    fields: { farm_name: "North Ridge Farms", country: "Canada" },
  },
  {
    name: "key ordering (declared out of order)",
    participant_type: "producer",
    external_id: "cs-0002",
    fields: { zebra: "last", alpha: "first", Mango: "capital M sorts before lowercase" },
  },
  {
    name: "unicode values and keys (ensure_ascii=False)",
    participant_type: "producer",
    external_id: "cs-0003-\u00e9\u4e2d",
    fields: { "caf\u00e9": "Montr\u00e9al", "\u4e2d\u6587": "\u5317\u4eac", emoji: "\ud83c\udf3e harvest" },
  },
  {
    name: "nested objects and arrays",
    participant_type: "buyer",
    external_id: "cs-0004",
    fields: {
      primary_crops: ["Wheat", "Barley"],
      meta: { region: { code: "CA-ON", name: "Ontario" }, tags: ["a", "b"] },
      matrix: [[1, 2], [3, 4]],
    },
  },
  {
    name: "numeric edges (ints stay ints through the file)",
    participant_type: "producer",
    external_id: "cs-0005",
    fields: { zero: 0, int: 42, negative: -17, float: 1.5, small: 0.1, big: 1234567890123, exp: 1e21 },
  },
  {
    name: "null and empty containers",
    participant_type: "producer",
    external_id: "cs-0006",
    fields: { nothing: null, empty_obj: {}, empty_arr: [], empty_str: "" },
  },
  {
    name: "string escapes and control characters",
    participant_type: "producer",
    external_id: "cs-0007",
    fields: { quoted: 'He said "hi"', backslash: "C:\\path\\to", newline: "a\nb\tc", ctrl: "bell:\u0007 null:\u0000" },
  },
  {
    name: "booleans",
    participant_type: "buyer",
    external_id: "cs-0008",
    fields: { organic: true, certified: false },
  },
  {
    name: "empty fields object",
    participant_type: "buyer",
    external_id: "cs-0009",
    fields: {},
  },
]

const outPath = process.argv[2] || "watermark-vectors.json"
const secret = process.argv[3] || CONFORMANCE_SECRET

const payload = {
  algo: WATERMARK_ALGO,
  secret,
  note: "Generated by ClientSynth scripts/watermark-conformance.ts — Cosolvent must verify every record.",
  vectors: VECTORS.map(v => {
    const record = { participant_type: v.participant_type, external_id: v.external_id, fields: v.fields }
    return {
      name: v.name,
      // The canonical string is included so a mismatch reports *where* the two
      // implementations diverge, not merely that a signature failed.
      canonical: canonicalPayload(record),
      signature: sign(record, secret),
      record: stamp(record, secret),
    }
  }),
}

writeFileSync(outPath, JSON.stringify(payload, null, 2), "utf8")
console.log(`Wrote ${payload.vectors.length} conformance vectors to ${outPath}`)
